### ISSUE TITLE
trivial-gray-streams-tests does not build in latest sbcl 1.4.11

### ISSUE THREAD

**Issue by quicklisp** [trivial-gray-streams/trivial-gray-streams#9]
Full log here: http://report.quicklisp.org/2018-09-06/failure-report/trivial-gray-streams.html#trivial-gray-streams-test

I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/trivial-gray-streams/0fcc608f10ff593529a6d7283f40794100d3770f/trivial-gray-streams-20180906-git/test/test.lisp
    ; in: DEFUN RUN-TESTS
    ;     (READ-SEQUENCE #(1 2) TRIVIAL-GRAY-STREAMS-TEST::S :START 0 :END 1)
    ; 
    ; caught WARNING:
    ;   Destructive function READ-SEQUENCE called on constant data: #(1 2)
    ;   See also:
    ;     The ANSI Standard, Special Operator QUOTE
    ;     The ANSI Standard, Section 3.2.2.3
    Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10006005B3}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "trivial-gray-streams-test" "test">

**Comment by avodonosov** [comment]
I indeed call (read-sequence #(1 2) ...) here
https://github.com/trivial-gray-streams/trivial-gray-streams/blob/cbe363def3c5cfd71017ad37ed9ad789e684cba6/test/test.lisp#L190

Why is that invalid... it's not Special Operator Quote

**Comment by avodonosov** [comment]
For the record: (read-sequence #(1 2) ...) is invalid because of http://www.lispworks.com/documentation/HyperSpec/Body/03_ga.htm
